import { COMMANDS, EXPIRES, GROUPS, SHELLS, commandOf, type ArgKind, type FlagSpec, type ValueKind } from "./commands.js";

/**
 * Tab completion (PETTY-274), the way `gh` and `kubectl` do it: each shell's script is a small wrapper
 * that calls `petty __complete` with the words typed so far and shows what it prints, one candidate a
 * line. The logic lives here, so an upgrade never leaves a stale script behind.
 *
 * Names (items, drawers, tags, places) come live from Petty with the stored login, decrypted for this
 * Tab press only and never cached on disk (rule 1). Offline, signed out or slow: nothing is offered.
 */
export type Shell = (typeof SHELLS)[number];

/** Live names, fetched once per Tab press; null when there is no login or no answer in time. */
export interface Names {
  readonly items: readonly string[];
  readonly drawers: readonly string[];
  readonly tags: readonly string[];
  readonly places: readonly string[];
  readonly itemTags: (item: string) => Promise<readonly string[]>;
}

const TOP = [...new Set(COMMANDS.filter((c) => !c.hidden).map((c) => c.name.split(" ")[0]!))];

function flagSpec(flags: readonly FlagSpec[], word: string): FlagSpec | undefined {
  if (word.startsWith("--")) return flags.find((f) => f.name === word.slice(2).split("=")[0]);
  if (/^-[a-z]$/.test(word)) return flags.find((f) => f.short === word.slice(1));
  return undefined;
}

/** What to offer for the word being typed. `prior`: the words before it, after the program's name. */
export async function candidates(prior: readonly string[], cur: string, names: () => Promise<Names | null>, hosts: readonly string[]): Promise<string[]> {
  const pick = (list: readonly string[]) => {
    const c = cur.toLocaleLowerCase();
    return [...new Set(list)].filter((x) => x.toLocaleLowerCase().startsWith(c));
  };
  if (prior.length === 0) return pick(cur.startsWith("-") ? ["--help", "--version"] : [...TOP, "help"]);
  if (prior.length === 1 && (GROUPS as readonly string[]).includes(prior[0]!)) {
    return pick(COMMANDS.filter((c) => c.name.startsWith(`${prior[0]} `)).map((c) => c.name.split(" ")[1]!));
  }
  if (prior[0] === "help" && prior.length === 1) return pick(TOP);
  const found = commandOf(prior);
  if (!found || found.spec.hidden) return [];
  const { spec, used } = found;

  // walk what follows the command: which positional comes next, and whether a flag waits for its value
  const positionals: string[] = [];
  let waiting: FlagSpec | undefined;
  for (const w of prior.slice(used)) {
    if (waiting) { waiting = undefined; continue; }
    const f = flagSpec(spec.flags, w);
    if (f) { if (f.value && !w.includes("=")) waiting = f; continue; }
    positionals.push(w);
  }
  if (waiting) return pick(await values(waiting.value!, names, hosts));
  if (cur.startsWith("-")) return pick(spec.flags.flatMap((f) => [`--${f.name}`, ...(f.short ? [`-${f.short}`] : [])]).concat("--help"));
  const arg = spec.args[Math.min(positionals.length, spec.args.length - 1)];
  if (!arg || (positionals.length >= spec.args.length && !arg.rest)) return [];
  return pick(await argValues(arg.kind, positionals, names));
}

async function values(kind: ValueKind, names: () => Promise<Names | null>, hosts: readonly string[]): Promise<readonly string[]> {
  switch (kind) {
    case "host": return hosts;
    case "expires": return EXPIRES;
    case "shell": return SHELLS;
    case "place": return (await names())?.places ?? [];
    case "tag": return (await names())?.tags ?? [];
    default: return [];
  }
}

async function argValues(kind: ArgKind, positionals: readonly string[], names: () => Promise<Names | null>): Promise<readonly string[]> {
  if (kind === "shell") return SHELLS;
  if (kind === "text" || kind === "amount") return [];
  const n = await names();
  if (!n) return [];
  if (kind === "item") return n.items;
  if (kind === "drawer") return n.drawers;
  if (kind === "tag") return n.tags;
  if (kind === "place") return n.places;
  return positionals[0] ? n.itemTags(positionals[0]) : [];
}

/** How each shell wants a candidate printed. bash inserts it as is, so its specials are escaped. */
export function forShell(shell: string | undefined, candidate: string): string {
  return shell === "bash" ? candidate.replace(/([\s'"\\$`!&;|<>(){}*?#~[\]])/g, "\\$1") : candidate;
}

/** The word being typed, as the shell passed it: bash and zsh keep the backslashes and an opening quote. */
export const unquote = (word: string): string => word.replace(/^["']/, "").replace(/\\(.)/g, "$1");

const HEAD = "petty Tab completion (PETTY-274). Generated by: petty completion";

export function script(shell: Shell): string {
  switch (shell) {
    case "bash":
      return `# ${HEAD} -s bash
# Load it from ~/.bashrc:  eval "$(petty completion -s bash)"
_petty_complete() {
  # the words are taken before IFS changes: bash 3.2 (macOS) joins a sliced array under another IFS
  local words=("\${COMP_WORDS[@]:1:COMP_CWORD}")
  local IFS=$'\\n'
  COMPREPLY=($(PETTY_COMPLETE_SHELL=bash petty __complete "\${words[@]}" 2>/dev/null))
}
complete -o default -F _petty_complete petty
`;
    case "zsh":
      return `#compdef petty
# ${HEAD} -s zsh
# Load it:  petty completion -s zsh > "\${fpath[1]}/_petty"  (then open a new shell),
#     or:   eval "$(petty completion -s zsh)" in ~/.zshrc, after compinit.
_petty() {
  local -a found
  found=("\${(@f)$(PETTY_COMPLETE_SHELL=zsh petty __complete "\${(@)words[2,CURRENT]}" 2>/dev/null)}")
  [[ -n "\${found[1]}" ]] && compadd -- "\${found[@]}"
}
if [[ "\${funcstack[1]}" == "_petty" ]]; then
  _petty "$@"
else
  compdef _petty petty
fi
`;
    case "fish":
      return `# ${HEAD} -s fish
# Load it:  petty completion -s fish > ~/.config/fish/completions/petty.fish
function __petty_complete
    set -l prior (commandline -opc)
    set -e prior[1]
    set -l cur (commandline -ct)
    set -lx PETTY_COMPLETE_SHELL fish
    set -lx PETTY_COMPLETE_CURRENT "=$cur"
    petty __complete $prior 2>/dev/null
end
complete -c petty -f -a '(__petty_complete)'
`;
    case "powershell":
      return `# ${HEAD} -s powershell
# Load it from $PROFILE:  petty completion -s powershell | Out-String | Invoke-Expression
Register-ArgumentCompleter -Native -CommandName petty -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $prior = @($commandAst.CommandElements | Select-Object -Skip 1 | Where-Object { $_.Extent.EndOffset -le $cursorPosition } | ForEach-Object { $_.ToString() })
    if ($wordToComplete -ne '' -and $prior.Count -gt 0) { $prior = @($prior | Select-Object -SkipLast 1) }
    $env:PETTY_COMPLETE_SHELL = 'powershell'
    $env:PETTY_COMPLETE_CURRENT = '=' + $wordToComplete
    try {
        petty __complete @prior 2>$null | ForEach-Object {
            $text = if ($_ -match "[\\s'\`"]") { "'" + ($_ -replace "'", "''") + "'" } else { $_ }
            [System.Management.Automation.CompletionResult]::new($text, $_, 'ParameterValue', $_)
        }
    } finally {
        Remove-Item Env:PETTY_COMPLETE_SHELL, Env:PETTY_COMPLETE_CURRENT -ErrorAction SilentlyContinue
    }
}
`;
  }
}
